apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-nginx-kustomize
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: nginx-kustomize
          image: nginx
          ports:
            - containerPort: 80
