bitnami-redis:  
  # Copyright Broadcom, Inc. All Rights Reserved.
  # SPDX-License-Identifier: APACHE-2.0

  ## @section Global parameters
  ## Global Docker image parameters
  ## Please, note that this will override the image parameters, including dependencies, configured to use the global value
  ## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
  ##

  ## @param global.imageRegistry Global Docker image registry
  ## @param global.imagePullSecrets Global Docker registry secret names as an array
  ## @param global.defaultStorageClass Global default StorageClass for Persistent Volume(s)
  ## @param global.storageClass DEPRECATED: use global.defaultStorageClass instead
  ## @param global.redis.password Global Redis&reg; password (overrides `auth.password`)
  ##
  global:
    redis:
      password: "test-password-random-123!"
