apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: vle-dev
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/krzysztofsol/argocd-multiple-source-public.git
        revision: HEAD
        files:
          - path: "apps/**/overlays/vle-dev/kustomize.json"
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: "{{ .appName }}"
      name: "vle-dev-{{ .appName }}"
      namespace: argocd
    spec:
      project: default
      source:
        path: "{{ .srcPath }}"
        repoURL: https://github.com/krzysztofsol/argocd-multiple-source-public.git
        targetRevision: HEAD
      destination:
        name: in-cluster
        namespace: "{{ .destNamespace }}"
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: false
        retry:
          limit: 1
          backoff:
            factor: 1
